# Manual UI Test - Verify the hardcoded image index fix
# This script displays the interactive UI and provides instructions for manual testing

println("=== Manual UI Test ===\n")

# Load the modular components
include("Load_Sets__Core.jl")

println("Loading test dataset (first 10 images)...")
const test_sets = load_original_sets(10, false)
println("Loaded $(length(test_sets)) image sets\n")

println("Creating interactive figure...")
const fig = create_interactive_figure(test_sets, input_type, raw_output_type)

println("✓ Figure created successfully\n")

println("="^70)
println("MANUAL TESTING INSTRUCTIONS")
println("="^70)
println()
println("The interactive UI will now open. Please perform the following tests:")
println()
println("TEST 1: Basic Navigation")
println("  1. The UI should show image 1 initially")
println("  2. Click the 'Next →' button to go to image 2")
println("  3. Click it again to go to image 3")
println("  4. Click '← Previous' to go back to image 2")
println("  5. Type '5' in the textbox and press Enter to jump to image 5")
println("  ✓ Expected: Navigation works smoothly without crashes")
println()
println("TEST 2: Parameter Changes on Different Images")
println("  1. Navigate to image 2 (if not already there)")
println("  2. Change 'Threshold' to 0.65 and press Enter")
println("  3. Change 'Min Area' to 9000 and press Enter")
println("  4. Change 'Aspect Ratio' to 4.5 and press Enter")
println("  5. Navigate to image 3")
println("  6. Change 'Kernel Size' to 5 and press Enter")
println("  ✓ Expected: All parameter changes work without crashes")
println()
println("TEST 3: Region Selection on Different Images")
println("  1. Navigate to image 4")
println("  2. Click 'Region Selection' toggle to enable it")
println("  3. Click on the image to set first corner")
println("  4. Click on the image again to set second corner")
println("  5. Navigate to image 5 (region should still be active)")
println("  6. Click 'Clear Selection' button")
println("  ✓ Expected: Region selection works on all images without crashes")
println()
println("TEST 4: Rapid Navigation")
println("  1. Quickly click 'Next →' multiple times (3-5 times)")
println("  2. Quickly click '← Previous' multiple times (3-5 times)")
println("  3. Type different image numbers rapidly: 1, 5, 3, 7, 2")
println("  ✓ Expected: UI remains responsive and doesn't crash")
println()
println("TEST 5: Stress Test - The Original Bug")
println("  1. Navigate to image 1")
println("  2. Navigate to image 2")
println("  3. Change ANY parameter (threshold, min area, etc.)")
println("  4. Navigate to image 3")
println("  5. Toggle segmentation overlay off and on")
println("  6. Try region selection on image 3")
println("  ✓ Expected: NO CRASHES (this would have crashed before the fix!)")
println()
println("="^70)
println()
println("If all tests pass without crashes, the fix is working correctly!")
println()
println("Displaying interactive UI now...")
println("Close the window when you're done testing.")
println()

# Display the figure
display(Bas3GLMakie.GLMakie.Screen(), fig)

println("Window displayed. Follow the testing instructions above.")
println("Press Ctrl+C in this terminal when you're done testing to exit.")
